import type { HelpSearchEntry } from '@/helpers/helpSearch'

export const HELP_CONTENT: HelpSearchEntry[] = [
  { id: 'getting-started', title: 'getting started', section: 'basics', summary: 'add colors, lock the ones you want to keep, and reroll the rest.', keywords: ['begin', 'start', 'first palette', 'new palette', 'make a palette', 'make colors', 'create colors', 'create a palette', 'color palette generator', 'palette creator', 'how does this work', 'quick start', 'add color', 'random color', 'reroll colors', 'generate colors', 'generate a color palette', 'start a color palette', 'keep a color', 'maximum colors', 'ten colors'], shortcuts: ['a', 'space', 'r'], related: ['palette', 'relationships', 'presets', 'keyboard'] },
  { id: 'palette', title: 'palette', section: 'basics', summary: 'lock, reroll, edit, delete, and copy individual colors.', keywords: ['swatch', 'swatches', 'palette colors', 'color circle', 'hex code', 'individual color', 'lock color', 'lock swatch', 'unlock color', 'keep color', 'freeze color', 'reroll one color', 'regenerate color', 'replace color', 'remove swatch', 'remove color', 'delete color', 'copy hex', 'palette controls', 'ten color limit', 'reorder colors'], shortcuts: ['1-9, 0'], related: ['edit-mode', 'variations', 'copy-formats'] },
  { id: 'undo-redo', title: 'undo & redo', section: 'basics', summary: 'move backward or forward through palette changes in the current session.', keywords: ['history', 'go back', 'go forward', 'revert', 'reverse change', 'restore change', 'mistake', 'accident', 'previous palette', 'recover deleted color', 'command z', 'control z', 'cmd z', 'ctrl z', 'redo change', 'session history'], shortcuts: ['z', 'shift+z'], related: ['palette', 'getting-started'] },
  { id: 'relationships', title: 'color relationships', section: 'basics', summary: 'generate colors using complementary, analogous, triadic, and other hue relationships.', keywords: ['color theory', 'color wheel', 'hue relationship', 'color scheme', 'color combinations', 'color combos', 'color pairing', 'matching palette', 'complementary', 'analogous', 'triadic', 'tetradic', 'split complementary', 'monochromatic', 'opposite color', 'neighboring colors', 'matching colors', 'coordinating colors', 'colors that go together', 'harmonic palette', 'random relationship'], shortcuts: ['q'], related: ['presets', 'harmony'] },
  { id: 'presets', title: 'presets', section: 'basics', summary: 'generate palettes in pastel, neon, earth, jewel, warm, cool, and muted styles.', keywords: ['style', 'mood', 'look', 'theme palette', 'pastel', 'soft colors', 'neon', 'bright colors', 'earth tones', 'earthy', 'jewel tones', 'warm colors', 'cool colors', 'muted colors', 'desaturated', 'vibrant', 'random preset', 'next preset', 'previous preset'], shortcuts: ['p', 'shift+p'], related: ['relationships', 'palette'] },
  { id: 'save-open', title: 'save & open', section: 'storage', summary: 'save palettes in this browser and open them again later.', keywords: ['save palette', 'save colors', 'open palette', 'open saved palette', 'load palette', 'saved palettes', 'my palettes', 'my color palettes', 'store palette', 'recover palette', 'lost palette', 'find palette', 'rename palette', 'delete saved palette', 'browser storage', 'local storage', 'localstorage', 'where are palettes stored', 'persistence', 'keep for later', 'no account', 'offline data'], shortcuts: ['s', 'o'], related: ['collections', 'tags', 'backup'] },
  { id: 'collections', title: 'collections', section: 'storage', summary: 'group saved palettes and filter the open and save dialogs.', keywords: ['folder', 'palette folders', 'organize palettes', 'organize saved palettes', 'organize color palettes', 'group palettes', 'sort palettes', 'palette library', 'project palettes', 'categorize', 'category', 'album', 'create collection', 'rename collection', 'delete collection', 'move palette', 'filter collection', 'all palettes', 'uncategorized'], related: ['save-open', 'tags'] },
  { id: 'tags', title: 'tags', section: 'storage', summary: 'label saved palettes and combine tags with text and collection filters.', keywords: ['label palette', 'keyword palette', 'metadata', 'search saved palettes', 'find saved palette', 'filter palettes', 'tag chip', 'multiple tags', 'combine filters', 'comma separated', 'retag palette', 'edit tags', 'project label'], related: ['collections', 'save-open'] },
  { id: 'backup', title: 'import / export palettes', section: 'storage', summary: 'back up all saved palettes to json or restore them in another browser.', keywords: ['backup', 'backup palettes', 'restore', 'restore palettes', 'import backup', 'export backup', 'export saved palettes', 'json backup', 'palette archive', 'download my data', 'move palettes', 'transfer palettes', 'migrate browser', 'new computer', 'another browser', 'recover saved palettes', 'portable backup', 'import json', 'export json', 'merge palettes', 'replace palettes'], related: ['save-open', 'export'] },
  { id: 'copy-formats', title: 'copy formats', section: 'copy & share', summary: 'copy colors as hex, rgb, hsl, css variables, tailwind, or scss.', keywords: ['clipboard', 'copy color', 'copy palette', 'hex', 'hex code', 'rgb', 'rgba', 'hsl', 'css variable', 'css custom property', 'css vars', 'tailwind config', 'tailwind colors', 'scss variable', 'sass', 'code snippet', 'developer format', 'frontend code', 'web development', 'paste colors'], related: ['share', 'export'] },
  { id: 'share', title: 'share via url', section: 'copy & share', summary: 'copy a link containing the palette colors and lock state.', keywords: ['share palette', 'share link', 'send colors', 'send palette', 'copy link', 'palette link', 'url', 'permalink', 'collaborate', 'show someone', 'send to client', 'send to teammate', 'share online', 'browser link', 'query string', 'locked colors in link', 'no account sharing'], shortcuts: ['c'], related: ['copy-formats', 'export'] },
  { id: 'export', title: 'export', section: 'export', summary: 'send a palette to code, image, and design-tool formats.', keywords: ['download palette', 'export palette', 'export colors', 'download colors', 'save as png', 'download swatches', 'export file', 'design software', 'design app', 'art app', 'creative app', 'adobe', 'adobe swatch exchange', 'ase', 'aco', 'photoshop', 'adobe photoshop', 'illustrator', 'adobe illustrator', 'procreate', 'procreate swatches', 'clip studio', 'clip studio paint', 'csp', 'gimp', 'gpl', 'gimp palette', 'krita', 'paint.net', 'paint net', 'paintnet', 'swatch file', 'import swatches', 'color set', 'palette file', 'css file', 'json file', 'tailwind file', 'scss file', 'sass file', 'svg', 'png', 'image export', 'vertical palette', 'horizontal palette', 'circle palette', 'transparent background', 'shift cmd e', 'shift control e', 'shift ctrl e'], shortcuts: ['e', 'shift+command+e'], related: ['copy-formats', 'backup', 'share', 'gradient'] },
  { id: 'edit-mode', title: 'edit mode', section: 'color tools', summary: 'enter exact hex, hsl, or oklch values and pick a color from the screen.', keywords: ['edit color', 'change color', 'replace color', 'exact color', 'precise color', 'manual color', 'enter hex', 'hex input', 'hex editor', 'three digit hex', 'six digit hex', 'invalid hex', 'hsl picker', 'hue slider', 'saturation slider', 'lightness slider', 'oklch', 'color values', 'live preview', 'confirm edit', 'cancel edit', 'discard edit', 'per color editor'], shortcuts: ['shift+alt+1-9, 0'], related: ['color-picker', 'variations'] },
  { id: 'gradient', title: 'gradient generator', section: 'color tools', summary: 'arrange palette-linked or custom color stops and export the gradient.', keywords: ['linear gradient', 'css gradient', 'background gradient', 'color ramp', 'blend colors', 'color transition', 'gradient stop', 'color stop', 'add stop', 'remove stop', 'move stop', 'drag stop', 'custom stop', 'linked stop', 'gradient angle', 'gradient direction', 'degrees', 'aspect ratio', 'landscape gradient', 'square gradient', 'portrait gradient', 'rebuild from palette', 'gradient css', 'gradient tailwind', 'gradient svg', 'gradient png', 'wallpaper', 'banner'], shortcuts: ['g', 'e'], related: ['export', 'preview', 'palette'] },
  { id: 'preview', title: 'palette preview', section: 'color tools', summary: 'test colors in bars, title designs, posters, and interface examples.', keywords: ['visualize palette', 'test palette', 'see colors in use', 'colors in context', 'mockup', 'full screen', 'fullscreen', 'mosaic', 'color bars', 'title design', 'typography', 'hero design', 'editorial', 'poster', 'ui mockup', 'interface mockup', 'website mockup', 'app mockup', 'dashboard', 'shadcn', 'color roles', 'background color', 'primary color', 'accent color', 'muted color', 'font preview', 'corner radius', 'design system'], shortcuts: ['f'], related: ['contrast', 'harmony'] },
  { id: 'extract', title: 'extract from image', section: 'color tools', summary: 'find dominant colors in an image and choose which ones to add.', keywords: ['image to palette', 'photo to palette', 'picture to palette', 'colors from image', 'colors from photo', 'extract colors', 'dominant colors', 'sample image', 'upload image', 'import image', 'drag and drop image', 'png image', 'jpg image', 'jpeg image', 'gif image', 'webp image', 'k means', 'kmeans', 'transparent pixels', 'pick colors from photo'], shortcuts: ['x'], related: ['palette', 'color-picker', 'edit-mode', 'harmony'] },
  { id: 'color-picker', title: 'color picker', section: 'color tools', summary: 'pick a color from the screen or use the operating-system picker.', keywords: ['eyedropper', 'eye dropper', 'pipette', 'sample screen', 'sample pixel', 'pick pixel', 'pick from screen', 'screen color', 'desktop color', 'color sampler', 'system picker', 'operating system picker', 'eyedropper api', 'browser picker', 'chrome picker', 'chromium picker', 'choose color visually'], shortcuts: ['i'], related: ['edit-mode', 'palette'] },
  { id: 'color-naming', title: 'color naming', section: 'color tools', summary: 'view the nearest descriptive and css color names for each swatch.', keywords: ['what color is this', 'name this color', 'color name', 'descriptive name', 'nearest color name', 'common color name', 'css color name', 'css named color', 'named color', 'swatch name', 'color label', 'human readable color', 'delta e', 'oklab distance'], related: ['palette', 'copy-formats'] },
  { id: 'variations', title: 'variations', section: 'color tools', summary: 'generate tints, shades, and tones from one palette color.', keywords: ['color variants', 'color scale', 'color ramp', 'lighter color', 'darker color', 'make color lighter', 'make color darker', 'tint', 'shade', 'tone', 'mix with white', 'mix with black', 'mix with gray', 'muted version', 'lightness steps', 'derived colors', 'same color variations'], shortcuts: ['v then 1-9, 0'], related: ['edit-mode', 'palette'] },
  { id: 'harmony', title: 'harmony score', section: 'color tools', summary: 'review hue spacing, saturation consistency, and lightness range.', keywords: ['palette score', 'rate palette', 'evaluate palette', 'do colors work together', 'colors clash', 'clashing colors', 'pleasing colors', 'balanced palette', 'discordant palette', 'inconsistent palette', 'color harmony', 'hue spacing', 'saturation consistency', 'lightness range', 'relationship bonus', 'high contrast score', 'why is score low'], shortcuts: ['y'], related: ['relationships', 'contrast', 'preview', 'variations'] },
  { id: 'reduced-motion', title: 'reduced motion', section: 'accessibility', summary: 'understand how paletteport follows the operating-system motion preference.', keywords: ['animation', 'movement', 'transition', 'disable animation', 'turn off animation', 'less animation', 'motion sickness', 'dizzy', 'vestibular', 'prefers reduced motion', 'prefers-reduced-motion', 'operating system preference', 'os motion setting', 'accessibility motion', 'instant transitions', 'theme wipe'], related: ['theme', 'color-blindness'] },
  { id: 'color-blindness', title: 'color blindness', section: 'accessibility', summary: 'simulate common color-vision differences on palette colors.', keywords: ['color blind', 'colour blind', 'color vision deficiency', 'colour vision deficiency', 'cvd', 'colorblind simulator', 'accessibility simulation', 'red green color blind', 'blue yellow color blind', 'deuteranopia', 'deutan', 'protanopia', 'protan', 'tritanopia', 'tritan', 'simulate vision', 'accessible palette'], shortcuts: ['shift+t'], related: ['contrast', 'preview'] },
  { id: 'contrast', title: 'contrast checker', section: 'accessibility', summary: 'compare palette pairs against wcag aa, aaa, and large-text thresholds.', keywords: ['readability', 'legibility', 'hard to read', 'text hard to see', 'accessible colors', 'accessibility check', 'wcag', 'wcag 2', 'aa', 'aaa', 'contrast ratio', 'color contrast', 'text contrast', 'background contrast', 'foreground background', 'large text', 'normal text', 'pass fail', 'minimum contrast', 'which colors for text'], shortcuts: ['k', 'shift+k'], related: ['color-blindness', 'preview'] },
  { id: 'theme', title: 'theme', section: 'reference', summary: 'switch between light, gray, and dark workspace themes.', keywords: ['appearance', 'workspace appearance', 'light mode', 'dark mode', 'gray mode', 'grey mode', 'neutral background', 'background theme', 'switch theme', 'cycle theme', 'display mode', 'color surround', 'viewing environment', 'system appearance'], shortcuts: ['t'], related: ['reduced-motion', 'contrast'] },
  { id: 'error-recovery', title: 'error recovery', section: 'reference', summary: 'recover from an unexpected render failure without clearing local palettes.', keywords: ['crash', 'blank', 'broken', 'reload', 'reset', 'failure'], related: ['save-open', 'backup'] },
  { id: 'keyboard', title: 'keyboard shortcuts', section: 'reference', summary: 'view every keyboard command grouped by palette, file, view, and general actions.', keywords: ['hotkey', 'hotkeys', 'key command', 'key commands', 'keyboard controls', 'keyboard navigation', 'cheat sheet', 'shortcut list', 'all shortcuts', 'commands', 'keys', 'faster workflow', 'power user', 'without mouse', 'what key', 'question mark', 'slash key', 'shift slash'], shortcuts: ['?'], related: ['getting-started', 'palette', 'export'] },
]

export const HELP_SECTIONS = ['basics', 'storage', 'copy & share', 'export', 'color tools', 'accessibility', 'reference']

export function getHelpEntry(pageId: string) {
  return HELP_CONTENT.find((entry) => entry.id === pageId)
}
